# docker-compose.dev.yml
version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    networks:
      - app-net
    depends_on:
      - ollama

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app-net
    stdin_open: true
    tty: true

  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/ollama-data:/root/.ollama
    networks:
      - app-net
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]


volumes:
  ollama-data:

networks:
  app-net: