FROM golang:1.24.4-alpine

# Tools für Air
RUN apk add --no-cache git curl tar

# Air installieren (richtiger Pfad!)
RUN go install github.com/air-verse/air@latest

WORKDIR /app

# Nur Mod-Dateien zuerst (für Caching)
COPY go.mod ./
COPY go.sum ./
RUN go mod download

# Jetzt den Code
COPY . .

EXPOSE 3000

# Starte Air (liegt in /go/bin)
CMD ["/go/bin/air"]