# docker-compose.dev.yml
version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    networks:
      - app-net
    depends_on:
      - ollama

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app-net
    stdin_open: true
    tty: true

  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/ollama-data:/root/.ollama
    networks:
      - app-net
    deploy:
      resources:
        limits:
            cpus: '6.0' # Limit CPU usage to 6 cores
            memory: 32G # Limit memory usage to 32GB
        reservations:
          devices:
            - capabilities: [gpu]

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 59LWrt!mDo6GC4
      MYSQL_DATABASE: health_coach
      TZ: Europe/Berlin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net


volumes:
  mysql_data:

networks:
  app-net: